version: '3.9'

services:
  cinema-rest:
    container_name: cinema-rest
    image: cinema-rest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cinema-rest-network
    depends_on:
      - postgres
  postgres:
    image: postgres:14.3
    networks:
      - cinema-rest-network
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: "cinema_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  postgres:

networks:
  cinema-rest-network: