server:
  port: 8081

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://10.40.1.9:5432/cinema_db
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://10.40.1.9:5432/cinema_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:cinema
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    url: jdbc:h2:mem:cinema
    user: sa
    password: