server:
  port: 8081

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/cinema_db
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:cinema_db_test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    url: jdbc:h2:mem:cinema_db_test;DB_CLOSE_DELAY=-1
    user: sa
    password: