server:
  port: 8080

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/cinema_db
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/cinema_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/cinema_db
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/cinema_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver