server:
  port: 8081

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/cinema_db
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver